export const topics = [
  {
    id: "failure-workflow",
    category: "safety",
    eyebrow: "RELIABILITY LAYER",
    title: "Your workflow failed.",
    highlight: "Who finds out first?",
    promise: "A production workflow needs a second workflow that watches it.",
    steps: ["Catch the error", "Capture the input", "Alert the owner", "Link to the failed run"],
    mistake: "A silent failure is more expensive than a visible error.",
    outcome: "Add one shared error handler before adding another automation.",
    voiceScript: "Your automation is not finished when the happy path works. Build one error workflow that catches every failed run, records the input, alerts the owner, and links back to the execution. That turns a silent failure into a five minute fix. Do this before you build another fancy workflow. Save the pattern, and get my free n eight n starter templates through the link in bio.",
  },
  {
    id: "duplicate-proof-leads",
    category: "safety",
    eyebrow: "DUPLICATE PROTECTION",
    title: "Never email a lead",
    highlight: "twice by accident.",
    promise: "Retries are normal. Duplicate actions do not have to be.",
    steps: ["Create a unique lead key", "Check the sent log", "Send only if missing", "Write the key after success"],
    mistake: "A retry without an idempotency check can repeat the real-world action.",
    outcome: "Use a stable key around every email, invoice, or CRM update.",
    voiceScript: "One timeout can make an automation retry, and suddenly your lead gets the same email twice. Give every action a unique key. Check a sent log before the action, send only when the key is missing, and write it after success. This tiny pattern makes retries safe. Save it for your next n eight n workflow, and find two free starter templates through the link in bio.",
  },
  {
    id: "daily-lead-digest",
    category: "starter-workflows",
    eyebrow: "STARTER WORKFLOW",
    title: "One lead digest.",
    highlight: "Zero inbox hunting.",
    promise: "Turn scattered enquiries into one ranked morning brief.",
    steps: ["Read new enquiries", "Normalize the fields", "Rank by buying intent", "Send one daily digest"],
    mistake: "Do not add AI until simple rules can rank the obvious cases.",
    outcome: "Review one list at 9 AM instead of checking four tools all day.",
    voiceScript: "Stop checking four tools for new leads. Build one daily n eight n digest. Read new enquiries, normalize the fields, rank the obvious buying signals, and send one morning brief. Start with rules you can explain. Add A I only for the ambiguous messages later. You get one list at nine A M and fewer missed opportunities. The free starter templates are in my bio.",
  },
  {
    id: "invoice-reminders",
    category: "starter-workflows",
    eyebrow: "BORING = PROFITABLE",
    title: "Chase invoices",
    highlight: "without chasing people.",
    promise: "A small scheduled workflow can recover hours every month.",
    steps: ["Run every weekday", "Find overdue invoices", "Choose reminder stage", "Log the message sent"],
    mistake: "Never send without checking payment status again at the last moment.",
    outcome: "Consistent reminders, a clean audit trail, and less awkward admin.",
    voiceScript: "Here is a boring automation that can save real money. Every weekday, find overdue invoices, check payment status one last time, choose the correct reminder stage, then log the message. No autonomous agent needed. The important parts are the final payment check and the sent log. Build boring systems before impressive ones. Save this, and grab my free n eight n templates from the bio.",
  },
  {
    id: "ai-one-step",
    category: "ai-agents",
    eyebrow: "USE AI PRECISELY",
    title: "Add one AI step.",
    highlight: "Not an AI agent.",
    promise: "AI is easiest to trust when it solves one narrow judgment task.",
    steps: ["Automate the fixed rules", "Isolate the fuzzy decision", "Force structured output", "Route low confidence to a human"],
    mistake: "Do not let a model control the trigger, decision, and final action at once.",
    outcome: "One constrained model call is cheaper, clearer, and easier to test.",
    voiceScript: "You probably do not need an A I agent. Automate the fixed rules first. Isolate the one fuzzy decision, give the model a strict output format, and route low confidence results to a human. One constrained A I step is cheaper and easier to test than an agent controlling everything. Save this architecture, and use the free n eight n starter templates in my bio.",
  },
  {
    id: "human-approval",
    category: "ai-agents",
    eyebrow: "HUMAN IN THE LOOP",
    title: "Let AI draft.",
    highlight: "Let humans commit.",
    promise: "Approval gates keep high-impact automations fast and reversible.",
    steps: ["AI prepares the draft", "Store the proposed action", "Ask for approve or reject", "Execute only after approval"],
    mistake: "High confidence is not permission to send, delete, pay, or publish.",
    outcome: "Automate the preparation and keep one tap of human control.",
    voiceScript: "Use A I for speed, not irreversible permission. Let the model prepare a draft, store the proposed action, ask a human to approve or reject, and execute only after approval. This works for emails, payments, deletions, and publishing. You automate almost all the work while keeping one tap of control. Save the pattern. My free n eight n templates are in the bio.",
  },
  {
    id: "workflow-map",
    category: "workflow-design",
    eyebrow: "MAP BEFORE NODES",
    title: "Design the workflow",
    highlight: "on one page first.",
    promise: "Four boxes reveal most automation gaps before you open n8n.",
    steps: ["Trigger: what starts it?", "Input: what must exist?", "Action: what changes?", "Proof: how do we verify?"],
    mistake: "Starting with nodes hides missing business rules behind technical work.",
    outcome: "If four boxes are unclear, the automation is not ready to build.",
    voiceScript: "Before opening n eight n, draw four boxes. What starts the workflow? What input must exist? What real action changes? And how will you prove it worked? If any box is unclear, more nodes will not fix the process. This one page map prevents hours of rebuilding. Save it before your next automation, and get my free starter workflows from the link in bio.",
  },
  {
    id: "webhook-hardening",
    category: "workflow-design",
    eyebrow: "WEBHOOK CHECKLIST",
    title: "A webhook is a door.",
    highlight: "Add a lock.",
    promise: "Validate requests before they are allowed to trigger real work.",
    steps: ["Verify a secret", "Reject missing fields", "Limit payload size", "Return quickly, process later"],
    mistake: "A public URL should never trust the shape or source of its input.",
    outcome: "Validate first, acknowledge fast, and do slow work asynchronously.",
    voiceScript: "Treat every webhook like a public door. Verify a secret, reject missing fields, limit the payload, and return quickly before doing slow work. Never trust the source or shape of a public request. These four checks make your n eight n webhook safer and more reliable. Save the checklist, and find two free starter templates through the link in my bio.",
  },
  {
    id: "cloud-vs-self-hosted",
    category: "hosting",
    eyebrow: "N8N HOSTING",
    title: "Cloud or self-hosted?",
    highlight: "Price your attention.",
    promise: "The cheapest server is not always the cheapest way to run automation.",
    steps: ["Estimate workflow value", "Count maintenance hours", "Assess data constraints", "Choose for the next 90 days"],
    mistake: "Do not self-host only to avoid a fee while creating a weekly support job.",
    outcome: "Start with the option you can operate reliably, then revisit at scale.",
    voiceScript: "Cloud or self hosted n eight n? Do not compare only the monthly fee. Estimate the value of the workflow, count maintenance hours, check your data constraints, and choose for the next ninety days. A cheap server becomes expensive when it creates a weekly support job. Start with what you can operate reliably, then revisit at scale. Save this decision rule for later.",
  },
];
